[
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "**Is your feature request related to a problem? Please describe.**  I'm frustrated when I've joined my iOS device to a ZeroTier network, connected it, and then find that it has disconnected after some time of inactivity or link drop.    **Describe the solution yod like**  I'd like to be able to configure ZeroTier networks as _Always On_, or _Connect on Demand_ on my iOS device so that every request is made through my chosen ZeroTier network.    **Describe alternatives yove considered**  Building my own app is an option, but seems like an unnecessary duplication of effort.    **Additional context**  n/a  ",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/856/comments",
        "created_at": "2018-09-18T19:36:51Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/856/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/856",
        "id": 361451749,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/856/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNjE0NTE3NDk=",
        "number": 856,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/856/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Allow for Connect on Demand on iOS app",
        "updated_at": "2018-09-18T19:36:51Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/856",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/1731163?v=4",
            "events_url": "https://api.github.com/users/andrewtlove/events{/privacy}",
            "followers_url": "https://api.github.com/users/andrewtlove/followers",
            "following_url": "https://api.github.com/users/andrewtlove/following{/other_user}",
            "gists_url": "https://api.github.com/users/andrewtlove/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/andrewtlove",
            "id": 1731163,
            "login": "andrewtlove",
            "node_id": "MDQ6VXNlcjE3MzExNjM=",
            "organizations_url": "https://api.github.com/users/andrewtlove/orgs",
            "received_events_url": "https://api.github.com/users/andrewtlove/received_events",
            "repos_url": "https://api.github.com/users/andrewtlove/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/andrewtlove/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/andrewtlove/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/andrewtlove"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "**Alternative, faster ways to get help**  If you have just started using ZeroTier, here are some places to get help:  - my.zerotier.com has a _Community_ tab. It's a live chat with other users and the developers.   - [ZeroTier Knowledge Base](https://support.zerotier.com/knowledgebase.php?s=MQ__)  - www.zerotier.com has a Contact Us button  - email contact@zerotier.com    **Describe the bug**  When i try to connect to a Network, it's not working mostly. At the Bottom i can see \"ONLINE\", but it's not connected to the VPN. I must try 9-10 times before it's working.    **To Reproduce**  1. Connect to a network with the phone  2. In 60% of the cases, you are not connected and you cannot see the VPN Key in the Notification Bar    **Expected behavior**  I will connect to the network without these bug.     **Smartphone (please complete the following information):**   - Device: [Samsung Galaxy S6]   - OS: [Android]   - ZeroTier Version: [1.2.12]   - Version [7.0 Nougat]    **Additional context**  Add any other context about the problem here.  - ZeroTier Network Configuration   FetchIssues.egg-info README.md fetch.py fetch.pyc fetch_issues.sh foo.txt hello.pyc oauth.sh setup.py token.txt visualization IPv4 Network, no IPv6 because my ethernet at home doesn't support this   FetchIssues.egg-info README.md fetch.py fetch.pyc fetch_issues.sh foo.txt hello.pyc oauth.sh setup.py token.txt visualization Public Network   FetchIssues.egg-info README.md fetch.py fetch.pyc fetch_issues.sh foo.txt hello.pyc oauth.sh setup.py token.txt visualization Enabled Broadcast   FetchIssues.egg-info README.md fetch.py fetch.pyc fetch_issues.sh foo.txt hello.pyc oauth.sh setup.py token.txt visualization Standard/Uncustomized Flow Rules  - Firewall Config (try turning the firewall off)   FetchIssues.egg-info README.md fetch.py fetch.pyc fetch_issues.sh foo.txt hello.pyc oauth.sh setup.py token.txt visualization No Firewall on Android Devices  - General Network Environment: [ e.g Home, University Campus, Corporate LAN ]   FetchIssues.egg-info README.md fetch.py fetch.pyc fetch_issues.sh foo.txt hello.pyc oauth.sh setup.py token.txt visualization Home   FetchIssues.egg-info README.md fetch.py fetch.pyc fetch_issues.sh foo.txt hello.pyc oauth.sh setup.py token.txt visualization Cellular (With enabled Use Cellular Option in the App)    ",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/855/comments",
        "created_at": "2018-09-18T19:08:07Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/855/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/855",
        "id": 361441561,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/855/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNjE0NDE1NjE=",
        "number": 855,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/855/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Android Connection Problems",
        "updated_at": "2018-09-18T19:08:07Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/855",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/42975382?v=4",
            "events_url": "https://api.github.com/users/AsumYT/events{/privacy}",
            "followers_url": "https://api.github.com/users/AsumYT/followers",
            "following_url": "https://api.github.com/users/AsumYT/following{/other_user}",
            "gists_url": "https://api.github.com/users/AsumYT/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/AsumYT",
            "id": 42975382,
            "login": "AsumYT",
            "node_id": "MDQ6VXNlcjQyOTc1Mzgy",
            "organizations_url": "https://api.github.com/users/AsumYT/orgs",
            "received_events_url": "https://api.github.com/users/AsumYT/received_events",
            "repos_url": "https://api.github.com/users/AsumYT/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/AsumYT/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AsumYT/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/AsumYT"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "The JSON API for Central and the Controller uses integers that are larger than 53 bits of precision for timestamps. Unfortunately, in many languages and libraries, this means that these values will lose the low order bits of precision, because many libraries (and JavaScript itself) just use 64-bit floats for these values. So, for example, the current values on my system are 56 bits wide, which means that the low order 3 bits are lost.    Really the only \"safe\" way to deal with this is to provide an alternate form of representation. One option is to represent these as a string. Another option is to break the value up (often into high and low 32-bit dword values.)    Right now this affects my ability to use these with the JavaScript library I've chosen (cJSON). I will probably need to choose a different cJSON library for this, but the problem will affect others, and especially JavaScript users.",
        "closed_at": null,
        "comments": 3,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/854/comments",
        "created_at": "2018-09-18T17:18:43Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/854/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/854",
        "id": 361403390,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/854/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNjE0MDMzOTA=",
        "number": 854,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/854/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "In the Central & Controller API: 64-bit ints used in JSON",
        "updated_at": "2018-09-18T17:58:20Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/854",
        "user": {
            "avatar_url": "https://avatars2.githubusercontent.com/u/1295229?v=4",
            "events_url": "https://api.github.com/users/gdamore/events{/privacy}",
            "followers_url": "https://api.github.com/users/gdamore/followers",
            "following_url": "https://api.github.com/users/gdamore/following{/other_user}",
            "gists_url": "https://api.github.com/users/gdamore/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/gdamore",
            "id": 1295229,
            "login": "gdamore",
            "node_id": "MDQ6VXNlcjEyOTUyMjk=",
            "organizations_url": "https://api.github.com/users/gdamore/orgs",
            "received_events_url": "https://api.github.com/users/gdamore/received_events",
            "repos_url": "https://api.github.com/users/gdamore/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/gdamore/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/gdamore/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/gdamore"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Switch from using self-supplied to standards compliant versions of IP address to/from string/binary conversion functions.     The version in ZT didn't understand IPv6 :: (double-colon) syntax, and would improperly convert shorthand IPv6 strings into the wrong binary representation.     The version in ZT didn't generate shorthand IPv6 strings either, so this makes them easier to visually parse.    No change in IPv4 conversion other than using the standard library instead of ZT custom code.",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/853/comments",
        "created_at": "2018-09-17T20:18:52Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/853/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/pull/853",
        "id": 361027224,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/853/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjE2MTAyMzAw",
        "number": 853,
        "pull_request": {
            "diff_url": "https://github.com/zerotier/ZeroTierOne/pull/853.diff",
            "html_url": "https://github.com/zerotier/ZeroTierOne/pull/853",
            "patch_url": "https://github.com/zerotier/ZeroTierOne/pull/853.patch",
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/pulls/853"
        },
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/853/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Dev",
        "updated_at": "2018-09-17T20:18:52Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/853",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/2524251?v=4",
            "events_url": "https://api.github.com/users/darkain/events{/privacy}",
            "followers_url": "https://api.github.com/users/darkain/followers",
            "following_url": "https://api.github.com/users/darkain/following{/other_user}",
            "gists_url": "https://api.github.com/users/darkain/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/darkain",
            "id": 2524251,
            "login": "darkain",
            "node_id": "MDQ6VXNlcjI1MjQyNTE=",
            "organizations_url": "https://api.github.com/users/darkain/orgs",
            "received_events_url": "https://api.github.com/users/darkain/received_events",
            "repos_url": "https://api.github.com/users/darkain/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/darkain/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/darkain/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/darkain"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "I tried to use the documentation [here](https://my.zerotier.com/help/api) to write a client however there were 2 issues:    1. The api calls did not seem to follow the schema, there were quite a lot of big differences between what I got and what the docs said  2. There are a few `array` types however I don't know what the type of this array is, this meant I had to do a lot of manual work since I am using a typed language (Haskell). Otherwise I may have been able to generate everything.  ",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/852/comments",
        "created_at": "2018-09-17T17:10:58Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/852/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/852",
        "id": 360961914,
        "labels": [
            {
                "color": "fbca04",
                "default": false,
                "id": 49621835,
                "name": "cleanup",
                "node_id": "MDU6TGFiZWw0OTYyMTgzNQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/cleanup"
            },
            {
                "color": "d4c5f9",
                "default": false,
                "id": 81791837,
                "name": "web",
                "node_id": "MDU6TGFiZWw4MTc5MTgzNw==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/web"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/852/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNjA5NjE5MTQ=",
        "number": 852,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/852/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Documentation on API page incorrect",
        "updated_at": "2018-09-17T18:01:31Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/852",
        "user": {
            "avatar_url": "https://avatars2.githubusercontent.com/u/934267?v=4",
            "events_url": "https://api.github.com/users/shmish111/events{/privacy}",
            "followers_url": "https://api.github.com/users/shmish111/followers",
            "following_url": "https://api.github.com/users/shmish111/following{/other_user}",
            "gists_url": "https://api.github.com/users/shmish111/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/shmish111",
            "id": 934267,
            "login": "shmish111",
            "node_id": "MDQ6VXNlcjkzNDI2Nw==",
            "organizations_url": "https://api.github.com/users/shmish111/orgs",
            "received_events_url": "https://api.github.com/users/shmish111/received_events",
            "repos_url": "https://api.github.com/users/shmish111/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/shmish111/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shmish111/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/shmish111"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Right now IPv6 addressed are displayed using their long-form notation, which takes up needless additional space on smaller console windows.    Example:  ```  root@router-1:~ # zerotier-cli listpeers  ...  200 listpeers e4da7455b2 2001:41d0:0001:4982:0000:0000:0000:0001/52203;7653;7653 3809 1.2.5 LEAF  ```    That address should be condensed down to 2001:41d0:1:4982::1 - a 20 character reduction, making it fit on a 80 character width terminal.    Also, yes, I'm aware that not all addresses can be condensed, but this is common enough that it helps readability.",
        "closed_at": null,
        "comments": 9,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/850/comments",
        "created_at": "2018-09-14T18:29:49Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/850/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/850",
        "id": 360409265,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/850/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNjA0MDkyNjU=",
        "number": 850,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/850/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Display IPv6 addresses using condensed notation",
        "updated_at": "2018-09-17T19:10:46Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/850",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/2524251?v=4",
            "events_url": "https://api.github.com/users/darkain/events{/privacy}",
            "followers_url": "https://api.github.com/users/darkain/followers",
            "following_url": "https://api.github.com/users/darkain/following{/other_user}",
            "gists_url": "https://api.github.com/users/darkain/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/darkain",
            "id": 2524251,
            "login": "darkain",
            "node_id": "MDQ6VXNlcjI1MjQyNTE=",
            "organizations_url": "https://api.github.com/users/darkain/orgs",
            "received_events_url": "https://api.github.com/users/darkain/received_events",
            "repos_url": "https://api.github.com/users/darkain/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/darkain/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/darkain/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/darkain"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "**Describe the bug**  I have installed ZertoTier One on WIndows 7 and used the GUI to join a network which was then displayed in the GUI as expected. When the computer is rebooted however, the GUI has no details of the network and the Node ID is shown as unknown. Seecting \"Show Networks...\" display a window with a plain white background and nothing else.    The service is running and executing the command zerotier-cli shownetworks from the command prompt shows the connected network details as expected and ipconfig shows the interface with the expected IP address    Removing and re-installing ZeroTier One fixes the issue temporarily until the computer is rebooted again.    My WIndows 7 machine is a VMWare virtual machine but I do not see as this should make a difference. I don't have a physical Windows 7 machine.    **To Reproduce**  1. Install ZeroTier One  2. Join a network  3. Confirm GUI shows network information correctly and that machine is reachable o ZeroTier IP.  4. Reboot computer  5. Note that GUI no longer has details of the network (THIS IS THE ERROR)  6. Confirm that machine is still reachabe over ZeroTier IP  7. Confirm that command line client correclty displays details.  [zerotier_issue_win7.pdf](https://github.com/zerotier/ZeroTierOne/files/2378258/zerotier_issue_win7.pdf)    **Expected behavior**  In step 5 above it is expected that the GUI displays details of the connected network and allows management of that connection.    **Screenshots**  PDF document zerotier_issue_winz.pdf attached containing screenshots of this issue.    **Desktop (please complete the following information):**   - OS: Windows 7   - ZeroTier Version: 1.2.12   - Hardware: VMWare Virtul Machine  ",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/849/comments",
        "created_at": "2018-09-13T08:02:06Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/849/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/849",
        "id": 359784922,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/849/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTk3ODQ5MjI=",
        "number": 849,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/849/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "GUI client 1.2.12 not working on windows 7 after rebooot.",
        "updated_at": "2018-09-13T08:02:06Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/849",
        "user": {
            "avatar_url": "https://avatars2.githubusercontent.com/u/1258411?v=4",
            "events_url": "https://api.github.com/users/canidorichard/events{/privacy}",
            "followers_url": "https://api.github.com/users/canidorichard/followers",
            "following_url": "https://api.github.com/users/canidorichard/following{/other_user}",
            "gists_url": "https://api.github.com/users/canidorichard/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/canidorichard",
            "id": 1258411,
            "login": "canidorichard",
            "node_id": "MDQ6VXNlcjEyNTg0MTE=",
            "organizations_url": "https://api.github.com/users/canidorichard/orgs",
            "received_events_url": "https://api.github.com/users/canidorichard/received_events",
            "repos_url": "https://api.github.com/users/canidorichard/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/canidorichard/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/canidorichard/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/canidorichard"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "**Describe the bug**  Windows 10 Pro 1809 (Insider build 17758.1) will not reconnect to ZeroTier network after machine is rebooted. The ZeroTier service does not start despite being marked as enabled. This issue isn't limited to ZeroTier. The same behavior is observed with another third party service.     **To Reproduce**  Steps to reproduce the behavior:  1. Be running Windows 10 1809 (I've observed this on earlier 1809 Insider builds as well)  2. Install ZeroTier One client and join network and authorize device. Set ZeroTier One client to start with Windows.  3. ZeroTier One client will be fully functional - can access resources via ZeroTier network, ZeroTier Windows service will be running.  4. Reboot computer  5. Log back into Windows.  6. Observe ZeroTier One client will show node ID as unknown. ZeroTier service will not be running, still shows as automatic.   7. Exit ZeroTier One client. Start ZeroTier service, start ZeroTier One client, device re-joins ZeroTier network.    **Expected behavior**  After reboot, ZeroTier One client should be running (with option to start with Windows enabled) along with the ZeroTier service.    **Desktop (please complete the following information):**   - OS: Windows   - OS/Distribution Version: 10 Professional 1809 (Build 17758.1)   - ZeroTier Version 1.2.12   - Hardware Lenovo ThinkCentre    **Additional context**  I'm running ZeroTier on a home network. I have other Windows 10 Professional devices joined to the same network, running the same client version. When these devices reboot, the ZeroTier One client works as expected.     Similar behavior has been observed on Windows Server 2016, although it's more random. Sometimes the service starts as expected, other times after a reboot the service will not start automatically.    I have not seen any errors in the Event Viewer related to this issue.    I figured I would file a bug report about this now since Windows 10 1809 is expected out in about a months time or sooner.    ",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/847/comments",
        "created_at": "2018-09-13T01:50:35Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/847/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/847",
        "id": 359712556,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/847/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTk3MTI1NTY=",
        "number": 847,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/847/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "ZeroTier One Client issue on Windows 10 1809 (Build 17758.1)",
        "updated_at": "2018-09-13T01:50:35Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/847",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/3200699?v=4",
            "events_url": "https://api.github.com/users/tnewton1/events{/privacy}",
            "followers_url": "https://api.github.com/users/tnewton1/followers",
            "following_url": "https://api.github.com/users/tnewton1/following{/other_user}",
            "gists_url": "https://api.github.com/users/tnewton1/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/tnewton1",
            "id": 3200699,
            "login": "tnewton1",
            "node_id": "MDQ6VXNlcjMyMDA2OTk=",
            "organizations_url": "https://api.github.com/users/tnewton1/orgs",
            "received_events_url": "https://api.github.com/users/tnewton1/received_events",
            "repos_url": "https://api.github.com/users/tnewton1/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/tnewton1/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tnewton1/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/tnewton1"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "CONTRIBUTOR",
        "body": "Reported by self-hosted user; I tested again my.zerotier.com     With a /24, at some point, it starts giving out already taken addresses.     With just a /30, it just doesn't hand out any more addresses. ",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/834/comments",
        "created_at": "2018-08-23T18:03:15Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/834/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/834",
        "id": 353491932,
        "labels": [
            {
                "color": "eb6420",
                "default": true,
                "id": 37169101,
                "name": "bug",
                "node_id": "MDU6TGFiZWwzNzE2OTEwMQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/bug"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/834/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTM0OTE5MzI=",
        "number": 834,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/834/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Controller - Can sometimes give out duplicate v4 auto-assign addresses",
        "updated_at": "2018-08-27T21:44:06Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/834",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/11598?v=4",
            "events_url": "https://api.github.com/users/laduke/events{/privacy}",
            "followers_url": "https://api.github.com/users/laduke/followers",
            "following_url": "https://api.github.com/users/laduke/following{/other_user}",
            "gists_url": "https://api.github.com/users/laduke/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/laduke",
            "id": 11598,
            "login": "laduke",
            "node_id": "MDQ6VXNlcjExNTk4",
            "organizations_url": "https://api.github.com/users/laduke/orgs",
            "received_events_url": "https://api.github.com/users/laduke/received_events",
            "repos_url": "https://api.github.com/users/laduke/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/laduke/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/laduke/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/laduke"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "For all tested Windows devices (6 PCs, Windows 7 and Windows 10), the UI doesn't update itself after performing any of the following actions (from the UI):    - Joining a network  - Leaving a network  - Deleting a network    The changes are only displayed after quitting and starting the program again. This does not only apply to the main menu, but also the \"show networks\" dialog, even when (re-)opened after a change (joining/deleting/creating a network).",
        "closed_at": null,
        "comments": 3,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/832/comments",
        "created_at": "2018-08-20T07:58:48Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/832/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/832",
        "id": 352024496,
        "labels": [
            {
                "color": "5319e7",
                "default": true,
                "id": 37169105,
                "name": "question",
                "node_id": "MDU6TGFiZWwzNzE2OTEwNQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/question"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/832/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTIwMjQ0OTY=",
        "number": 832,
        "reactions": {
            "+1": 3,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 3,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/832/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Windows: UI doesn't update without restart",
        "updated_at": "2018-09-17T18:44:32Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/832",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/6317548?v=4",
            "events_url": "https://api.github.com/users/theCalcaholic/events{/privacy}",
            "followers_url": "https://api.github.com/users/theCalcaholic/followers",
            "following_url": "https://api.github.com/users/theCalcaholic/following{/other_user}",
            "gists_url": "https://api.github.com/users/theCalcaholic/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/theCalcaholic",
            "id": 6317548,
            "login": "theCalcaholic",
            "node_id": "MDQ6VXNlcjYzMTc1NDg=",
            "organizations_url": "https://api.github.com/users/theCalcaholic/orgs",
            "received_events_url": "https://api.github.com/users/theCalcaholic/received_events",
            "repos_url": "https://api.github.com/users/theCalcaholic/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/theCalcaholic/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/theCalcaholic/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/theCalcaholic"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "When I check the listening ports by ZeroTierOne, I find, excpet the port 9993, ZeroTierOne also listens some other random ports, such as, 51727, 51728 at present.   Can I set ZeroTierOne listen some specific ports, instead random ports? I'm using the port range 20000-30000, once one or two ports are used by ZeroTierOne, my app cannot run successfully.",
        "closed_at": null,
        "comments": 5,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/831/comments",
        "created_at": "2018-08-20T01:50:22Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/831/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/831",
        "id": 351958561,
        "labels": [
            {
                "color": "bfe5bf",
                "default": false,
                "id": 166317741,
                "name": "backlog",
                "node_id": "MDU6TGFiZWwxNjYzMTc3NDE=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/backlog"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/831/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTE5NTg1NjE=",
        "number": 831,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/831/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Disable binding random ports",
        "updated_at": "2018-09-11T03:37:05Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/831",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/6284797?v=4",
            "events_url": "https://api.github.com/users/yanggis/events{/privacy}",
            "followers_url": "https://api.github.com/users/yanggis/followers",
            "following_url": "https://api.github.com/users/yanggis/following{/other_user}",
            "gists_url": "https://api.github.com/users/yanggis/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/yanggis",
            "id": 6284797,
            "login": "yanggis",
            "node_id": "MDQ6VXNlcjYyODQ3OTc=",
            "organizations_url": "https://api.github.com/users/yanggis/orgs",
            "received_events_url": "https://api.github.com/users/yanggis/received_events",
            "repos_url": "https://api.github.com/users/yanggis/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/yanggis/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yanggis/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/yanggis"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "I'm [working on packaging zerotier with habitat](https://github.com/habitat-sh/core-plans/pull/1674), which creates can deploy services in isolated runtime environments. Habitat needs to control what directory the service runs out of, ideally being able to change it both at build time and at run time. I had to patch `osdep/OSUtils.cpp` to let habitat change it at build time, and it would be helpful to be able to change it at runtime too. I explored first creating wrapper scripts for all zerotier's commands that would pass the environmental home directory as a CLI argument, but that was messy and inhibited users from from using that CLI argument for their own purposes    It would be greatly helpful to my efforts and I believe useful for other novel deployment techniques if [`platformDefaultHomePath()`](https://github.com/zerotier/ZeroTierOne/blob/3de7691af306f86b5b3aa6fb15777841e9ba1388/osdep/OSUtils.cpp#L381) would use the value of an environment value like `ZEROTIER_HOME` if it's set",
        "closed_at": null,
        "comments": 4,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/829/comments",
        "created_at": "2018-08-18T00:17:41Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/829/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/829",
        "id": 351772743,
        "labels": [
            {
                "color": "009800",
                "default": true,
                "id": 37169103,
                "name": "enhancement",
                "node_id": "MDU6TGFiZWwzNzE2OTEwMw==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/enhancement"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/829/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTE3NzI3NDM=",
        "number": 829,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/829/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Enable environment to override default home path",
        "updated_at": "2018-09-11T12:05:06Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/829",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/458494?v=4",
            "events_url": "https://api.github.com/users/themightychris/events{/privacy}",
            "followers_url": "https://api.github.com/users/themightychris/followers",
            "following_url": "https://api.github.com/users/themightychris/following{/other_user}",
            "gists_url": "https://api.github.com/users/themightychris/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/themightychris",
            "id": 458494,
            "login": "themightychris",
            "node_id": "MDQ6VXNlcjQ1ODQ5NA==",
            "organizations_url": "https://api.github.com/users/themightychris/orgs",
            "received_events_url": "https://api.github.com/users/themightychris/received_events",
            "repos_url": "https://api.github.com/users/themightychris/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/themightychris/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/themightychris/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/themightychris"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Hello, I'm using ZeroTier Central to manage connected devices to my networks. But some devices that were approved before gets randomly denied after some time. It's really hard to reproduce, so I want to ask is there a way to debug this and fix it? I think that this is the problem is not on the client side but on the ZeroTier Central.    ",
        "closed_at": null,
        "comments": 2,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/828/comments",
        "created_at": "2018-08-17T11:46:25Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/828/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/828",
        "id": 351563362,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/828/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTE1NjMzNjI=",
        "number": 828,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/828/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Some devices get randomly denied",
        "updated_at": "2018-09-11T04:14:52Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/828",
        "user": {
            "avatar_url": "https://avatars3.githubusercontent.com/u/14824142?v=4",
            "events_url": "https://api.github.com/users/dec0dOS/events{/privacy}",
            "followers_url": "https://api.github.com/users/dec0dOS/followers",
            "following_url": "https://api.github.com/users/dec0dOS/following{/other_user}",
            "gists_url": "https://api.github.com/users/dec0dOS/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/dec0dOS",
            "id": 14824142,
            "login": "dec0dOS",
            "node_id": "MDQ6VXNlcjE0ODI0MTQy",
            "organizations_url": "https://api.github.com/users/dec0dOS/orgs",
            "received_events_url": "https://api.github.com/users/dec0dOS/received_events",
            "repos_url": "https://api.github.com/users/dec0dOS/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/dec0dOS/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dec0dOS/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/dec0dOS"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Hello,    Since Fedora now supports armv6hl and aarch64 for raspberry pi officially, its possible to package the armv7hl version too?    ```  [root@minigate ~]# uname -a   Linux minigate 4.17.12-200.fc28.armv7hl #1 SMP Fri Aug 3 16:09:35 UTC 2018 armv7l armv7l armv7l GNU/Linux  [root@minigate ~]# dnf install zerotier  \u00daltima verifica\u00e7\u00e3o de data de vencimento de metadados: 0:06:46 atr\u00e1s em ter 14 ago 2018 10:07:56 -03.  Nenhuma correspond\u00eancia para argumento: zerotier  Erro: N\u00e3o foi poss\u00edvel encontrar uma correspond\u00eancia  [root@minigate ~]# cat /etc/yum.repos.d/zerotier.repo   [zerotier]  name=ZeroTier, Inc. RPM Release Repository  baseurl=http://download.zerotier.com/redhat/fc/$releasever/  enabled=1  gpgcheck=1  [root@minigate ~]#   ```    Thanks",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/826/comments",
        "created_at": "2018-08-14T13:16:35Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/826/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/826",
        "id": 350423489,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/826/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTA0MjM0ODk=",
        "number": 826,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/826/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "[Request] Fedora packaging for armv7hl",
        "updated_at": "2018-08-14T13:16:35Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/826",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/201189?v=4",
            "events_url": "https://api.github.com/users/leleobhz/events{/privacy}",
            "followers_url": "https://api.github.com/users/leleobhz/followers",
            "following_url": "https://api.github.com/users/leleobhz/following{/other_user}",
            "gists_url": "https://api.github.com/users/leleobhz/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/leleobhz",
            "id": 201189,
            "login": "leleobhz",
            "node_id": "MDQ6VXNlcjIwMTE4OQ==",
            "organizations_url": "https://api.github.com/users/leleobhz/orgs",
            "received_events_url": "https://api.github.com/users/leleobhz/received_events",
            "repos_url": "https://api.github.com/users/leleobhz/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/leleobhz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/leleobhz/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/leleobhz"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "We've been updating to 1.2.12 and have found that on a small number of machines the `apt install zerotier-one=1.2.12` fails to restart the zerotier-one service once it has complete. Unfortunately haven't been able to spot a trend as there is nothing in the apt output and the service log only shows the service being shut down. This has happened on Ubuntu 14, 16 and 18.",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/825/comments",
        "created_at": "2018-08-14T10:30:52Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/825/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/825",
        "id": 350370148,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/825/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNTAzNzAxNDg=",
        "number": 825,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/825/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Upgrade to 1.2.12 sometimes fails to restart service",
        "updated_at": "2018-08-14T10:30:52Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/825",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/2863673?v=4",
            "events_url": "https://api.github.com/users/grantstephens/events{/privacy}",
            "followers_url": "https://api.github.com/users/grantstephens/followers",
            "following_url": "https://api.github.com/users/grantstephens/following{/other_user}",
            "gists_url": "https://api.github.com/users/grantstephens/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/grantstephens",
            "id": 2863673,
            "login": "grantstephens",
            "node_id": "MDQ6VXNlcjI4NjM2NzM=",
            "organizations_url": "https://api.github.com/users/grantstephens/orgs",
            "received_events_url": "https://api.github.com/users/grantstephens/received_events",
            "repos_url": "https://api.github.com/users/grantstephens/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/grantstephens/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/grantstephens/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/grantstephens"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "The FileDB.cpp was lacking the functionality to actually delete members from networks.   This patch allows to delete the .json files corresponding to members in any given network.    Signed-off-by: Diego Schulz <dschulz@gmail.com>",
        "closed_at": null,
        "comments": 1,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/822/comments",
        "created_at": "2018-08-02T21:19:58Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/822/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/pull/822",
        "id": 347178709,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/822/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjA1ODY0NjQw",
        "number": 822,
        "pull_request": {
            "diff_url": "https://github.com/zerotier/ZeroTierOne/pull/822.diff",
            "html_url": "https://github.com/zerotier/ZeroTierOne/pull/822",
            "patch_url": "https://github.com/zerotier/ZeroTierOne/pull/822.patch",
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/pulls/822"
        },
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/822/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Add functionality to erase members from networks using file backend i\u2026",
        "updated_at": "2018-08-02T21:36:39Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/822",
        "user": {
            "avatar_url": "https://avatars2.githubusercontent.com/u/36960?v=4",
            "events_url": "https://api.github.com/users/dschulz/events{/privacy}",
            "followers_url": "https://api.github.com/users/dschulz/followers",
            "following_url": "https://api.github.com/users/dschulz/following{/other_user}",
            "gists_url": "https://api.github.com/users/dschulz/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/dschulz",
            "id": 36960,
            "login": "dschulz",
            "node_id": "MDQ6VXNlcjM2OTYw",
            "organizations_url": "https://api.github.com/users/dschulz/orgs",
            "received_events_url": "https://api.github.com/users/dschulz/received_events",
            "repos_url": "https://api.github.com/users/dschulz/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/dschulz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dschulz/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/dschulz"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Hi all,    I'm working on a simple Qt/C++ GUI cross-platform application to interact with the ZeroTier API (both node and controller). It's in very early stage now.    I've been skimming through the code of the controller API microservice and noticed that the HTTP status codes returned are always **200 OK** for successful operations, even for POST and DELETE. [Here's an example](https://github.com/zerotier/ZeroTierOne/blob/d55c732e1915affd2f40321261bb8178fa28f95a/controller/EmbeddedNetworkController.cpp#L1013).    Wouldn't it be desirable to return more semantically correct HTTP status codes like **201 Created** in the case of POST requests and **204 No Content** ?",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/820/comments",
        "created_at": "2018-07-27T14:25:53Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/820/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/820",
        "id": 345246728,
        "labels": [
            {
                "color": "bfe5bf",
                "default": false,
                "id": 166317741,
                "name": "backlog",
                "node_id": "MDU6TGFiZWwxNjYzMTc3NDE=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/backlog"
            },
            {
                "color": "c7def8",
                "default": false,
                "id": 81781561,
                "name": "compatibility",
                "node_id": "MDU6TGFiZWw4MTc4MTU2MQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/compatibility"
            },
            {
                "color": "207de5",
                "default": false,
                "id": 115904977,
                "name": "usability",
                "node_id": "MDU6TGFiZWwxMTU5MDQ5Nzc=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/usability"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/820/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDUyNDY3Mjg=",
        "number": 820,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/820/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "[question] Controller REST API and HTTP status return codes",
        "updated_at": "2018-09-10T22:16:37Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/820",
        "user": {
            "avatar_url": "https://avatars2.githubusercontent.com/u/36960?v=4",
            "events_url": "https://api.github.com/users/dschulz/events{/privacy}",
            "followers_url": "https://api.github.com/users/dschulz/followers",
            "following_url": "https://api.github.com/users/dschulz/following{/other_user}",
            "gists_url": "https://api.github.com/users/dschulz/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/dschulz",
            "id": 36960,
            "login": "dschulz",
            "node_id": "MDQ6VXNlcjM2OTYw",
            "organizations_url": "https://api.github.com/users/dschulz/orgs",
            "received_events_url": "https://api.github.com/users/dschulz/received_events",
            "repos_url": "https://api.github.com/users/dschulz/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/dschulz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dschulz/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/dschulz"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Hello!    A thing isn't clear and reliable for me is about how ZeroTier handles horizontal and vertical handover. In a symptomatic perspective, changing from a 802.11 to LTE can in worst case take more than 3 minutes to reach the network. Unlikelly I used to think, the worst case is when I change from NATed network to double NATed network (I think IPv6 to IPv4 may be worst, but no). Since my mobile carrier - as example - only uses CGNAT prefixes, if I need for some reason to exit a NAT to a CGNAT+Android Tether network it tooks a life to come back. I've already experimented this kind of issue on other network handover type.    Speculatively speaking, after read https://zerotier.com/manual.shtml#2_1_1 I conclude ZT does not implement something like HMAC to allow a changed-address peer to reuse a existent connection (Receiving a packet from other address and accepting it since its authenticated) and allow other peer to restablish the return path again (Using hole punch or other techniques).    This differ from a bug report because handover isnt a issue and its a predictable behaviour. Handover costs time and vertical handovers specially loss a lot of packets. But I think the network convergence of ZT takes too long, longer than Skype - as example - that also use techiniques to mitigate handover effects.    So, what ZT can explain or even change about the way it does handover?    Thanks!",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/818/comments",
        "created_at": "2018-07-25T14:03:55Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/818/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/818",
        "id": 344457749,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/818/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDQ0NTc3NDk=",
        "number": 818,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/818/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "[Clarification] ZeroTier's handover mechanism",
        "updated_at": "2018-07-25T14:03:55Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/818",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/201189?v=4",
            "events_url": "https://api.github.com/users/leleobhz/events{/privacy}",
            "followers_url": "https://api.github.com/users/leleobhz/followers",
            "following_url": "https://api.github.com/users/leleobhz/following{/other_user}",
            "gists_url": "https://api.github.com/users/leleobhz/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/leleobhz",
            "id": 201189,
            "login": "leleobhz",
            "node_id": "MDQ6VXNlcjIwMTE4OQ==",
            "organizations_url": "https://api.github.com/users/leleobhz/orgs",
            "received_events_url": "https://api.github.com/users/leleobhz/received_events",
            "repos_url": "https://api.github.com/users/leleobhz/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/leleobhz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/leleobhz/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/leleobhz"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Some providers significantly reduce UDP speed, for example OVH on dedicated servers allows only 1.05 Mb/s UDP whilst 1Gb/s for TCP.    I wanted to replace Tinc by Zerotier, but Zerotier 1.28 on OVH servers performs worse than Tinc (if Tinc is configured to use 'TCPOnly=yes').   I must disabled Tinc device in /var/lib/zerotier/local.conf, because Zerotier initially routed traffic through Tinc. After that 'zerotier-cli listpeers' shows correct external addresses and port 9993, but I suppose traffic goes through some zerotier planet server.     Zerotier should be clever and fallback to TCP when available on port 9993.           ",
        "closed_at": null,
        "comments": 3,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/816/comments",
        "created_at": "2018-07-21T21:26:01Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/816/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/816",
        "id": 343357033,
        "labels": [
            {
                "color": "bfe5bf",
                "default": false,
                "id": 166317741,
                "name": "backlog",
                "node_id": "MDU6TGFiZWwxNjYzMTc3NDE=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/backlog"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/816/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDMzNTcwMzM=",
        "number": 816,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/816/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "TCP as first class P2P transport",
        "updated_at": "2018-07-26T13:03:54Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/816",
        "user": {
            "avatar_url": "https://avatars2.githubusercontent.com/u/28733050?v=4",
            "events_url": "https://api.github.com/users/kulheim/events{/privacy}",
            "followers_url": "https://api.github.com/users/kulheim/followers",
            "following_url": "https://api.github.com/users/kulheim/following{/other_user}",
            "gists_url": "https://api.github.com/users/kulheim/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/kulheim",
            "id": 28733050,
            "login": "kulheim",
            "node_id": "MDQ6VXNlcjI4NzMzMDUw",
            "organizations_url": "https://api.github.com/users/kulheim/orgs",
            "received_events_url": "https://api.github.com/users/kulheim/received_events",
            "repos_url": "https://api.github.com/users/kulheim/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/kulheim/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/kulheim/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/kulheim"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Whereas my ping round-trip-time over ZeroTier averages <7ms between two connected hosts (Client and Gateway), whenever there is another data transfer taking place that involves those two hosts, I experience significant packet loss and ping delays. The ping packet loss is 29%, and with these stats: `rtt min/avg/max/mdev = 5.085/2301.156/9978.148/2866.061 ms`.    The Client and Gateway hosts are both Ubuntu 16. I've spun these up in two independent data centers that don't add any additional firewall restrictions (such as a security group), and the Linux firewall rules on both hosts are permissive (default ACCEPT). I've also experienced the same performance characteristics when the client is macOS, although that wasn't in a data center. Note that I'm using IPv4.    Both Client and Gateway belong to the same ZeroTier network. The Gateway host is also configured as an internet gateway (following the knowledge base instructions). On the Client, if I run two \"speedof.me\" internet tests while at the same time I ping the ZeroTier IP for the Gateway, I experience these dropped packets and delays.    The baseline ping round trip time (over ZeroTier, without the transfer taking place between the Client and Gateway) is <7ms and there is no packet loss. The ping connects the two hosts directly (that is, ZeroTier is able to send its encrypted packets directly between these two hosts over UDP at all time).    I'd like to confirm external reproducibility of this issue, and I'd also like to understand in the optimistic case, what is possible here? Is ZeroTier positioned to respond well to this situation in general? Are the performance characteristics coming up because of something specific?    I notice very little resource overhead (negligible CPU) on both hosts, so I'm wondering what might be going on. These concerns also include the case where more than one client (this time, behind a NAT - but with the same external egress IP) is connecting to the Gateway, but I've run the test just involving one connecting client.",
        "closed_at": null,
        "comments": 4,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/815/comments",
        "created_at": "2018-07-19T19:00:57Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/815/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/815",
        "id": 342850781,
        "labels": [
            {
                "color": "006b75",
                "default": false,
                "id": 195824598,
                "name": "performance",
                "node_id": "MDU6TGFiZWwxOTU4MjQ1OTg=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/performance"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/815/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDI4NTA3ODE=",
        "number": 815,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/815/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Dropped and delayed packets while another network transfer is taking place",
        "updated_at": "2018-09-07T19:05:38Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/815",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/241275?v=4",
            "events_url": "https://api.github.com/users/Intensity/events{/privacy}",
            "followers_url": "https://api.github.com/users/Intensity/followers",
            "following_url": "https://api.github.com/users/Intensity/following{/other_user}",
            "gists_url": "https://api.github.com/users/Intensity/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Intensity",
            "id": 241275,
            "login": "Intensity",
            "node_id": "MDQ6VXNlcjI0MTI3NQ==",
            "organizations_url": "https://api.github.com/users/Intensity/orgs",
            "received_events_url": "https://api.github.com/users/Intensity/received_events",
            "repos_url": "https://api.github.com/users/Intensity/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Intensity/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Intensity/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Intensity"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Hey ,     I'm trying to install zerotier on an EdgeRouterX that is a MIPSel 32bit system, running debian based EdgeRouter X v1.10.3.     I tried installing from the mipsel.deb from `https://download.zerotier.com/debian/jessie/pool/main/z/zerotier-one/` but that did not work and all the installers did not work either. :(    Its a similar issue to #702 ",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/812/comments",
        "created_at": "2018-07-17T22:56:29Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/812/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/812",
        "id": 342117970,
        "labels": [
            {
                "color": "c7def8",
                "default": false,
                "id": 81781561,
                "name": "compatibility",
                "node_id": "MDU6TGFiZWw4MTc4MTU2MQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/compatibility"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/812/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDIxMTc5NzA=",
        "number": 812,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/812/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "How to Install ZeroTierOne on a mipsle32 system",
        "updated_at": "2018-07-20T22:55:42Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/812",
        "user": {
            "avatar_url": "https://avatars2.githubusercontent.com/u/21285954?v=4",
            "events_url": "https://api.github.com/users/Julian-Mentasti/events{/privacy}",
            "followers_url": "https://api.github.com/users/Julian-Mentasti/followers",
            "following_url": "https://api.github.com/users/Julian-Mentasti/following{/other_user}",
            "gists_url": "https://api.github.com/users/Julian-Mentasti/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Julian-Mentasti",
            "id": 21285954,
            "login": "Julian-Mentasti",
            "node_id": "MDQ6VXNlcjIxMjg1OTU0",
            "organizations_url": "https://api.github.com/users/Julian-Mentasti/orgs",
            "received_events_url": "https://api.github.com/users/Julian-Mentasti/received_events",
            "repos_url": "https://api.github.com/users/Julian-Mentasti/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Julian-Mentasti/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Julian-Mentasti/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Julian-Mentasti"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "After a discussion with some colleagues, we have some concerns:    > Has anyone ever audited zerotier?     Can you explain (e.g. based on programming methodology) why you think it's secure? E.g. I have the impression that you don't use a lot of networking or crypto libraries and instead provide implementations which you have partially copy-pasted (from reputable sources at the time, I will admit that), which results in longer term maintenance and security problems. All in all, it seems to be optimized for speed (presumably to look good in benchmarks), not security (other than in terms of buzzwords).     > Have you ever fuzzed this system?     You could potentially apply here: https://github.com/google/oss-fuzz.    > Has the daemon ever crashed after 1.0?    > What's the worst thing that will happen when the daemon is compromised?     > Why do you think you haven't made the same mistakes as OpenSSL?     I think the core idea is great, but I personally have some concerns over the implementation. I would love to see strong answers for the above to remove these doubts.",
        "closed_at": null,
        "comments": 3,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/811/comments",
        "created_at": "2018-07-16T19:21:48Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/811/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/811",
        "id": 341645297,
        "labels": [
            {
                "color": "5319e7",
                "default": true,
                "id": 37169105,
                "name": "question",
                "node_id": "MDU6TGFiZWwzNzE2OTEwNQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/question"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/811/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDE2NDUyOTc=",
        "number": 811,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/811/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Security questions",
        "updated_at": "2018-08-25T19:33:47Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/811",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/34454443?v=4",
            "events_url": "https://api.github.com/users/coretemp/events{/privacy}",
            "followers_url": "https://api.github.com/users/coretemp/followers",
            "following_url": "https://api.github.com/users/coretemp/following{/other_user}",
            "gists_url": "https://api.github.com/users/coretemp/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/coretemp",
            "id": 34454443,
            "login": "coretemp",
            "node_id": "MDQ6VXNlcjM0NDU0NDQz",
            "organizations_url": "https://api.github.com/users/coretemp/orgs",
            "received_events_url": "https://api.github.com/users/coretemp/received_events",
            "repos_url": "https://api.github.com/users/coretemp/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/coretemp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/coretemp/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/coretemp"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "This is essentially a reopening of https://github.com/zerotier/ZeroTierOne/issues/34 in which @adamierymenko wrote:     > Once out of beta, this will get done at some point.    I think it has been out of beta for quite some time and other than the heavily commented https://github.com/zerotier/ZeroTierOne/blob/master/node/Packet.hpp I was not able to find anything. I am quite happy to just operate with `Packet.hpp`, but this is certainly not the case for other people in our organisation.     ",
        "closed_at": null,
        "comments": 2,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/810/comments",
        "created_at": "2018-07-16T13:10:08Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/810/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/810",
        "id": 341512369,
        "labels": [
            {
                "color": "bfe5bf",
                "default": false,
                "id": 166317741,
                "name": "backlog",
                "node_id": "MDU6TGFiZWwxNjYzMTc3NDE=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/backlog"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/810/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDE1MTIzNjk=",
        "number": 810,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/810/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Protocol needs to be written up in RFC form",
        "updated_at": "2018-07-16T14:18:28Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/810",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/34454443?v=4",
            "events_url": "https://api.github.com/users/coretemp/events{/privacy}",
            "followers_url": "https://api.github.com/users/coretemp/followers",
            "following_url": "https://api.github.com/users/coretemp/following{/other_user}",
            "gists_url": "https://api.github.com/users/coretemp/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/coretemp",
            "id": 34454443,
            "login": "coretemp",
            "node_id": "MDQ6VXNlcjM0NDU0NDQz",
            "organizations_url": "https://api.github.com/users/coretemp/orgs",
            "received_events_url": "https://api.github.com/users/coretemp/received_events",
            "repos_url": "https://api.github.com/users/coretemp/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/coretemp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/coretemp/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/coretemp"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Ubuntu 18.04 LTS, fresh install from ISO.  Zero-Tier adapter initializes, but does not assign IP address  Output of `ip address`:  ```  3: ztppiy6cts: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc fq_codel state UNKNOWN group default qlen 1000     link/ether 6e:d5:bb:11:74:0d brd ff:ff:ff:ff:ff:ff   inet6 fe80::6cd5:bbff:fe11:740d/64 scope link   valid_lft forever preferred_lft forever  ```  Output of `hostname -I`: `104.251.214.59` -- this is the ens18 interface address)    No errors show in /var/log/syslog at boot. However, if I do `service zerotier-one reload` or `systemctl reload zerotier-one` I get the following  ```  4: ztppiy6cts: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc fq_codel state UNKNOWN group default qlen 1000     link/ether 6e:d5:bb:11:74:0d brd ff:ff:ff:ff:ff:ff   inet6 fe80::6cd5:bbff:fe11:740d/64 scope link   valid_lft forever preferred_lft forever  ```  and this line appears in /var/log/syslog  ```  Jul 15 18:42:31 vhub networkd-dispatcher: WARNING:Unknown index 4 seen, reloading interface list  ```  This node and four others were setup using the same script, and only this node is experiencing the issue. The nodes are at linode, vultr and at vpsdime (this node).   Information from `uname -a` from this node  `Linux vhub.vnc.news 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`  and from a couple of the working nodes  `Linux lin1.vnc.news 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`  `Linux vul1.vnc.news 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`    All nodes are running client version 1.2.8    The ZeroTier web interface shows this node online along with the others, as seen in this screenshot.  ![capture](https://user-images.githubusercontent.com/6446167/42739646-a56d45fc-8860-11e8-9647-71a0e3abd5a3.JPG)    Output of `zerotier-cli info` : `200 info 414e0dea77 1.2.8 ONLINE`  Output of `zerotier-cli listnetworks`:  ```  200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>  200 listnetworks e5cd7a9e1cf5946e vnc.news 6e:d5:bb:11:74:0d OK PRIVATE ztppiy6cts -  ```    I've tried leaving and joining the network. I've tried uninstalling and reinstalling ZeroTier. Where do I turn from here?     ",
        "closed_at": null,
        "comments": 5,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/809/comments",
        "created_at": "2018-07-16T00:16:39Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/809/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/809",
        "id": 341364394,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/809/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzNDEzNjQzOTQ=",
        "number": 809,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/809/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Failing to assign IP to network interface",
        "updated_at": "2018-07-22T01:09:39Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/809",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/6446167?v=4",
            "events_url": "https://api.github.com/users/cyclonebt/events{/privacy}",
            "followers_url": "https://api.github.com/users/cyclonebt/followers",
            "following_url": "https://api.github.com/users/cyclonebt/following{/other_user}",
            "gists_url": "https://api.github.com/users/cyclonebt/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cyclonebt",
            "id": 6446167,
            "login": "cyclonebt",
            "node_id": "MDQ6VXNlcjY0NDYxNjc=",
            "organizations_url": "https://api.github.com/users/cyclonebt/orgs",
            "received_events_url": "https://api.github.com/users/cyclonebt/received_events",
            "repos_url": "https://api.github.com/users/cyclonebt/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cyclonebt/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cyclonebt/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cyclonebt"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Have you considered push ZeroTier package to official Fedora repo?    How to [Join the package collection maintainers](https://fedoraproject.org/wiki/Join_the_package_collection_maintainers).    ",
        "closed_at": null,
        "comments": 2,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/807/comments",
        "created_at": "2018-07-10T08:05:52Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/807/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/807",
        "id": 339734338,
        "labels": [
            {
                "color": "5319e7",
                "default": true,
                "id": 37169105,
                "name": "question",
                "node_id": "MDU6TGFiZWwzNzE2OTEwNQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/question"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/807/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzMzk3MzQzMzg=",
        "number": 807,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/807/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Fedora official repository",
        "updated_at": "2018-07-23T14:25:41Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/807",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/5614476?v=4",
            "events_url": "https://api.github.com/users/tim77/events{/privacy}",
            "followers_url": "https://api.github.com/users/tim77/followers",
            "following_url": "https://api.github.com/users/tim77/following{/other_user}",
            "gists_url": "https://api.github.com/users/tim77/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/tim77",
            "id": 5614476,
            "login": "tim77",
            "node_id": "MDQ6VXNlcjU2MTQ0NzY=",
            "organizations_url": "https://api.github.com/users/tim77/orgs",
            "received_events_url": "https://api.github.com/users/tim77/received_events",
            "repos_url": "https://api.github.com/users/tim77/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/tim77/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tim77/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/tim77"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Add metrics based on ZT_IF_METRIC.  There are negative implications of this - when somebody connected over zerotiers enters network that is same as one routed through managed routes, it might result in data leak as data are send to nodes in different network directly (not over zt). However, this is what allegedly happens on other platforms due to high interface metric, so this makes this Linux consistent with other platforms (who are in majority and this is what most people want anyway).  It is not marvel of great engineering, but propagating something hrough zt code is not exactly easy.  Tested on Arch and Fedora.",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/806/comments",
        "created_at": "2018-07-04T15:07:29Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/806/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/pull/806",
        "id": 338310360,
        "labels": [],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/806/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTk5Mjc2MDQ1",
        "number": 806,
        "pull_request": {
            "diff_url": "https://github.com/zerotier/ZeroTierOne/pull/806.diff",
            "html_url": "https://github.com/zerotier/ZeroTierOne/pull/806",
            "patch_url": "https://github.com/zerotier/ZeroTierOne/pull/806.patch",
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/pulls/806"
        },
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/806/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Add Linux route metrics",
        "updated_at": "2018-07-04T15:07:29Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/806",
        "user": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/11160972?v=4",
            "events_url": "https://api.github.com/users/neVERberleRfellerER/events{/privacy}",
            "followers_url": "https://api.github.com/users/neVERberleRfellerER/followers",
            "following_url": "https://api.github.com/users/neVERberleRfellerER/following{/other_user}",
            "gists_url": "https://api.github.com/users/neVERberleRfellerER/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/neVERberleRfellerER",
            "id": 11160972,
            "login": "neVERberleRfellerER",
            "node_id": "MDQ6VXNlcjExMTYwOTcy",
            "organizations_url": "https://api.github.com/users/neVERberleRfellerER/orgs",
            "received_events_url": "https://api.github.com/users/neVERberleRfellerER/received_events",
            "repos_url": "https://api.github.com/users/neVERberleRfellerER/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/neVERberleRfellerER/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/neVERberleRfellerER/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/neVERberleRfellerER"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "I've set up a variety of Managed Routes within ZeroTier Central for testing, including an entry for default route (0.0.0.0/0, which I believe gets translated internally to 0.0.0.0/1 and 128.0.0.0/1 on the client).    The route entries that have a nonzero leading octet (like 10.42.0.0/16, 242.0.0.0/8) are successfully being propagated to the client (Linux Debian and Ubuntu), in that the routing table quickly shows those very entries just like they are provided in the ZeroTier UI.    However, any entry that begins with a leading zero octet (such as 0.0.0.0/3, 0.1.2.0/24, 0.1.0.0/16) is not being propagated in any way to the client.    A use case I have is to let a client connect to two ZeroTier networks, each of which provide outbound internet connectivity. When the \"primary\" one is connected (as I'd like it to be at all times), this shows in the routing table as 0.0.0.0/1 and 128.0.0.0/1. But when the \"secondary\" network is also enabled and connected, then routing entries like 0.0.0.0/2, 64.0.0.0/2, 128.0.0.0/2, and 192.0.0.0/2 are meant to override the first one in the routing table. This leaves the primary one as always valid and an acceptable fallback. But the secondary one carries the actual traffic when it is enabled.    It seems that what's in the way of this working is some kind of automated filtering on route entries that begin with a zero octet.",
        "closed_at": null,
        "comments": 2,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/804/comments",
        "created_at": "2018-07-02T19:14:03Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/804/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/804",
        "id": 337631580,
        "labels": [
            {
                "color": "5319e7",
                "default": true,
                "id": 37169105,
                "name": "question",
                "node_id": "MDU6TGFiZWwzNzE2OTEwNQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/question"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/804/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzMzc2MzE1ODA=",
        "number": 804,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/804/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "ZeroTier Central managed routes with a leading zero octet aren't being reflected on the client",
        "updated_at": "2018-07-17T02:13:00Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/804",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/241275?v=4",
            "events_url": "https://api.github.com/users/Intensity/events{/privacy}",
            "followers_url": "https://api.github.com/users/Intensity/followers",
            "following_url": "https://api.github.com/users/Intensity/following{/other_user}",
            "gists_url": "https://api.github.com/users/Intensity/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Intensity",
            "id": 241275,
            "login": "Intensity",
            "node_id": "MDQ6VXNlcjI0MTI3NQ==",
            "organizations_url": "https://api.github.com/users/Intensity/orgs",
            "received_events_url": "https://api.github.com/users/Intensity/received_events",
            "repos_url": "https://api.github.com/users/Intensity/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Intensity/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Intensity/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Intensity"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "I'm running into an issue where I can't connect to any other hosts on my network from my phone, (iPhone X), when I am on the cellular network (T-Mobile). At first I wasn't able to connect even if I was on wifi but that was because my other VPN profiles were set to connect on-demand. Now that I have altered that setting, I can access hosts as long as I am on a wifi network of some sort but the second I switch to 4G the connection now longer works. I'm using Terminus and the only thing that it gives me is and invalid argument error.",
        "closed_at": null,
        "comments": 2,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/800/comments",
        "created_at": "2018-06-27T18:31:43Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/800/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/800",
        "id": 336340613,
        "labels": [
            {
                "color": "000000",
                "default": false,
                "id": 130619560,
                "name": "cantreproduce",
                "node_id": "MDU6TGFiZWwxMzA2MTk1NjA=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/cantreproduce"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/800/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzMzYzNDA2MTM=",
        "number": 800,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/800/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "iOS can't join over cellular network",
        "updated_at": "2018-07-20T23:02:43Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/800",
        "user": {
            "avatar_url": "https://avatars3.githubusercontent.com/u/36014547?v=4",
            "events_url": "https://api.github.com/users/peewee5/events{/privacy}",
            "followers_url": "https://api.github.com/users/peewee5/followers",
            "following_url": "https://api.github.com/users/peewee5/following{/other_user}",
            "gists_url": "https://api.github.com/users/peewee5/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/peewee5",
            "id": 36014547,
            "login": "peewee5",
            "node_id": "MDQ6VXNlcjM2MDE0NTQ3",
            "organizations_url": "https://api.github.com/users/peewee5/orgs",
            "received_events_url": "https://api.github.com/users/peewee5/received_events",
            "repos_url": "https://api.github.com/users/peewee5/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/peewee5/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/peewee5/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/peewee5"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Hi All,  Im hoping this issnt quite a NOOB question. But hi ho! hope someone can help me :-)    I have 3 edgemax Pro's that i want to do OSPF.    I have created on each router 1 interface for OSPF    R1 = 10.78.33.1  R2 = 10.78.33.2  R3= 10.78.33.3    These interfaces speak to one another using ZeroTier.   All im doing to get this going is in the GUI (keeping it simple for now) adding the 10.78.33.0/24 (OSPF interfaces) and then the networks i want each router to announce and for the others to learn.    When i set this up for 2 Routers it works fine. When i add in the next router the existing connection breaks. And i think i am doing something wrong! Not sure if its OSPF or ZeroT?     R1= 10.78.33.0/24, 10.49.97.0/24  R2= 10.78.33.0/24, 10.0.0.0/24  R3= 10.78.33.0/24, 10.0.1.0/24    so currently R3 and R2 are working perfectly. When i add in R! to the mix, R3 & and R2 break entirely. Cannot communicate at all.    Looking at documentation on UBNT i cant see anyone doing something similar to how i've set it up. Most people by the sounds of it. do this:     get R1 to R2 and R2 to R3 so R1 can talk to R3 via R2. But ultimately i dont want to do that.    I want the 3 routers to talk in the ZeroTier chat room swapping links.    Please someone tell me this is possible?     I have added 10.78.33.0/24 as a \"LAN\" under managed routes.     each site has a linux box bridging the ZT* interface to a virtual interface. This is then in a VLAN to the edgemax router. So that each router can talk in the chat room.     If dont implement OSPF all 3 routers speak fine.     Hope someone can help. ",
        "closed_at": null,
        "comments": 21,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/798/comments",
        "created_at": "2018-06-26T08:14:25Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/798/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/798",
        "id": 335706561,
        "labels": [
            {
                "color": "5319e7",
                "default": true,
                "id": 37169105,
                "name": "question",
                "node_id": "MDU6TGFiZWwzNzE2OTEwNQ==",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/question"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/798/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzMzU3MDY1NjE=",
        "number": 798,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/798/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "OSPF over ZeroTier",
        "updated_at": "2018-07-16T14:30:37Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/798",
        "user": {
            "avatar_url": "https://avatars3.githubusercontent.com/u/40593188?v=4",
            "events_url": "https://api.github.com/users/craig4who/events{/privacy}",
            "followers_url": "https://api.github.com/users/craig4who/followers",
            "following_url": "https://api.github.com/users/craig4who/following{/other_user}",
            "gists_url": "https://api.github.com/users/craig4who/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/craig4who",
            "id": 40593188,
            "login": "craig4who",
            "node_id": "MDQ6VXNlcjQwNTkzMTg4",
            "organizations_url": "https://api.github.com/users/craig4who/orgs",
            "received_events_url": "https://api.github.com/users/craig4who/received_events",
            "repos_url": "https://api.github.com/users/craig4who/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/craig4who/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/craig4who/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/craig4who"
        }
    },
    {
        "assignee": null,
        "assignees": [],
        "author_association": "NONE",
        "body": "Hi!    Since #651 it is possible to enter custom DNS when *adding* a network. However I don't see an option to *edit* the list of DNS servers once the network has been added. I have to delete and re-add the network to enter new DNS. Would it be possible to give the users the option to edit such settings for an existing network?",
        "closed_at": null,
        "comments": 0,
        "comments_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/790/comments",
        "created_at": "2018-06-14T09:46:31Z",
        "events_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/790/events",
        "html_url": "https://github.com/zerotier/ZeroTierOne/issues/790",
        "id": 332328603,
        "labels": [
            {
                "color": "bfe5bf",
                "default": false,
                "id": 166317741,
                "name": "backlog",
                "node_id": "MDU6TGFiZWwxNjYzMTc3NDE=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/backlog"
            },
            {
                "color": "207de5",
                "default": false,
                "id": 115904977,
                "name": "usability",
                "node_id": "MDU6TGFiZWwxMTU5MDQ5Nzc=",
                "url": "https://api.github.com/repos/zerotier/ZeroTierOne/labels/usability"
            }
        ],
        "labels_url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/790/labels{/name}",
        "locked": false,
        "milestone": null,
        "node_id": "MDU6SXNzdWUzMzIzMjg2MDM=",
        "number": 790,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/790/reactions"
        },
        "repository_url": "https://api.github.com/repos/zerotier/ZeroTierOne",
        "state": "open",
        "title": "Feature Request for Android: Edit DNS settings",
        "updated_at": "2018-06-18T18:21:54Z",
        "url": "https://api.github.com/repos/zerotier/ZeroTierOne/issues/790",
        "user": {
            "avatar_url": "https://avatars1.githubusercontent.com/u/633683?v=4",
            "events_url": "https://api.github.com/users/FloGa/events{/privacy}",
            "followers_url": "https://api.github.com/users/FloGa/followers",
            "following_url": "https://api.github.com/users/FloGa/following{/other_user}",
            "gists_url": "https://api.github.com/users/FloGa/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/FloGa",
            "id": 633683,
            "login": "FloGa",
            "node_id": "MDQ6VXNlcjYzMzY4Mw==",
            "organizations_url": "https://api.github.com/users/FloGa/orgs",
            "received_events_url": "https://api.github.com/users/FloGa/received_events",
            "repos_url": "https://api.github.com/users/FloGa/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/FloGa/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FloGa/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/FloGa"
        }
    }
]